version: '3.7'

services: 
  db:
    image: 'mysql:8.0.22'
    container_name: mysqldb
    ports: 
      - "3306:3306"

  api:
    image: springboot-task-tracker-mysql-k8s
    ports:
      - "8080-8085:8080"

volumes: 
  springboot-task-tracker-mysql-k8s-volume:

networks:
  default:
    name: springboot-task-tracker-mysql-k8s-network